Retrieve version metadata for CMD dataset edition
ONSdigital/dp-search-data-extractor pull request #27
Opened 2022-01-05 07:55 UTC by bpathak-ons

### What

* Retrieve version metadata for dataset edition 
* So that the service is able to search published contents for CMD and Cantabular datasets

### How to review

* Code make sense to achieve the objective, as above
* CI pass

### Who can review

Anyone

2022-01-06 23:00 UTC, rahulPalliyalil requested changes

2022-01-06 23:00 UTC, rahulPalliyalil commented on service/service_test.go
> +
(minor): extra space ?

2022-01-06 23:01 UTC, rahulPalliyalil commented
Looks good. Just some minor comments.

2022-01-07 17:18 UTC, bpathak-ons commented on handler/handler.go
> +		log.Info(ctx, "Invalid content data type received, no action")
nope. this can be a potential case which we don't need to worry about. Error needs to record/handle the err details too

2022-01-07 17:19 UTC, bpathak-ons commented on handler/handler.go
> +		return
duplicate

2022-01-10 12:01 UTC, rahulPalliyalil approved these changes

2022-01-10 17:19 UTC, merged