Retrieve content published
ONSdigital/dp-search-data-extractor pull request #5
Opened 2021-09-15 16:40 UTC by bpathak-ons

### What

* Retrieve content published from zebedee

### How to review

* All build, audit and unit test running fine

### Who can review

* Anyone but not me

2021-09-15 17:01 UTC, bpathak-ons commented on go.mod
> +	github.com/ONSdigital/dp-api-clients-go v1.41.1
remove this

2021-09-15 17:02 UTC, bpathak-ons commented on go.mod
> +replace github.com/ONSdigital/dp-api-clients-go => /Users/bhupendrapathak/go/src/github.com/ONSdigital/dp-api-clients-go
needs to be removed

2021-09-17 14:01 UTC, jessjenkins commented on service/service_test.go
> +				DoGetZebedeeClientFunc: funcDoGetZebedeeOk,
Also same issue for other scenarios following this one.

2021-09-17 18:39 UTC, bpathak-ons commented on event/consumer_test.go
> +// }
removed TODO comment and uncomment done

2021-09-21 10:10 UTC, cookel2 commented on go.mod
>  	github.com/ONSdigital/dp-component-test v0.3.0
The latest version of dp-component-test is 0.5.0

2021-09-21 13:01 UTC, bpathak-ons commented on go.mod
> +	github.com/ONSdigital/dp-api-clients-go/v2 v2.1.15-0.20210906102150-5521f44294e4
replaced

2021-09-21 13:09 UTC, cookel2 commented on event/handler_test.go
>  	Convey("Given a successful event handler, when Handle is triggered", t, func() {
This test is not very readable in my view. It seems to be missing a "Then" statement. I would suggest separating the "When" out from the "Given" statement too. Something like this: 
```suggestion
	Convey("Given an event handler, working successfully, and an event containing a URL", t, func() {
		var zebedeeMock = &eventMock.ZebedeeClientMock{GetPublishedDataFunc: getPublishDataFunc}
		eventHandler := &event.ContentPublishedHandler{zebedeeMock}
		filePath := "/tmp/dpSearchDataExtractor.txt"
		os.Remove(filePath)

		Convey("When the event handler is triggered", func() {
			err := eventHandler.Handle(testCtx, &config.Config{OutputFilePath: filePath}, &testEvent)

			Convey("Then the published data endpoint should be called, using the URL, and no error returned", func() {
				So(err, ShouldBeNil)
				So(zebedeeMock.GetPublishedDataCalls(), ShouldNotBeEmpty)
				So(zebedeeMock.GetPublishedDataCalls(), ShouldHaveLength, 1)
				So(zebedeeMock.GetPublishedDataCalls()[0].UriString, ShouldEqual, testEvent.URL)
			})
		})
	})
```

2021-09-21 13:11 UTC, cookel2 requested changes

2021-09-21 13:11 UTC, cookel2 commented on event/handler_test.go
> +	Convey("Given a un-successful event handler, when Handle is triggered", t, func() {
Similarly with this one I would have this: 
```suggestion
	Convey("Given an event handler, not working successfully, and an event containing a URL", t, func() {
		var zebedeeMockInError = &eventMock.ZebedeeClientMock{GetPublishedDataFunc: getPublishDataFuncInError}
		eventHandler := &event.ContentPublishedHandler{zebedeeMockInError}
		filePath := ""

		Convey("When the event handler is triggered", func() {
			err := eventHandler.Handle(testCtx, &config.Config{OutputFilePath: filePath}, &testEvent)

			Convey("Then the published data endpoint should be called, using the URL, and an error returned", func() {
				So(err, ShouldNotBeNil)
				So(err.Error(), ShouldEqual, errZebedee.Error())
				So(zebedeeMockInError.GetPublishedDataCalls(), ShouldNotBeEmpty)
				So(zebedeeMockInError.GetPublishedDataCalls(), ShouldHaveLength, 1)
				So(zebedeeMockInError.GetPublishedDataCalls()[0].UriString, ShouldEqual, testEvent.URL)
			})
		})
	})
```

2021-09-22 12:16 UTC, cookel2 approved these changes
looks good to me

2021-09-22 12:20 UTC, merged